import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/utils/horoscope_utils.dart';
import '../../../providers/profile_provider.dart';
import '../../../widgets/common/app_text_field.dart';
import '../../../widgets/common/gradient_button.dart';
import '../../../widgets/common/searchable_field.dart';

class Step3Horoscope extends ConsumerStatefulWidget {
  final VoidCallback onNext;
  const Step3Horoscope({super.key, required this.onNext});

  @override
  ConsumerState<Step3Horoscope> createState() => _Step3State();
}

class _Step3State extends ConsumerState<Step3Horoscope> {
  final _birthTimeController = TextEditingController();
  final _birthPlaceController = TextEditingController();
  String? _rasi;
  String? _nakshatra;
  String? _lagnam;
  bool _manualOverride = false;

  @override
  void dispose() {
    _birthTimeController.dispose();
    _birthPlaceController.dispose();
    super.dispose();
  }

  void _autoGenerate() {
    final data = ref.read(profileCreationProvider).data;
    final dobStr = data['dateOfBirth'] as String?;
    if (dobStr == null) return;
    final dob = DateTime.parse(dobStr);
    final time = _birthTimeController.text;
    setState(() {
      _rasi = HoroscopeUtils.calculateRasi(dob);
      _nakshatra = HoroscopeUtils.calculateNakshatra(dob);
      _lagnam = HoroscopeUtils.calculateLagnam(dob, time);
    });
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Horoscope auto-generated. You can edit if needed.')));
  }

  void _saveAndNext() {
    ref.read(profileCreationProvider.notifier).updateData({
      'horoscopeDetails': {
        'rasi': _rasi ?? '',
        'nakshatra': _nakshatra ?? '',
        'lagnam': _lagnam ?? '',
        'birthTime': _birthTimeController.text,
        'birthPlace': _birthPlaceController.text,
        'isAutoGenerated': !_manualOverride,
        'isUserEdited': _manualOverride,
        'isAstrologerVerified': false,
      },
    });
    widget.onNext();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Horoscope Details', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
          const SizedBox(height: 8),
          const Text('Enter birth details for auto-generation or fill manually.',
              style: TextStyle(color: Colors.grey)),
          const SizedBox(height: 24),
          AppTextField(
            controller: _birthTimeController,
            label: 'Birth Time',
            hint: 'HH:MM AM/PM',
          ),
          const SizedBox(height: 16),
          AppTextField(
            controller: _birthPlaceController,
            label: 'Birth Place',
            hint: 'City, State',
          ),
          const SizedBox(height: 16),
          OutlinedButton.icon(
            onPressed: _autoGenerate,
            icon: const Icon(Icons.auto_awesome),
            label: const Text('Auto-Generate Horoscope'),
            style: OutlinedButton.styleFrom(
              minimumSize: const Size.fromHeight(48),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Switch(
                value: _manualOverride,
                onChanged: (v) => setState(() => _manualOverride = v),
              ),
              const SizedBox(width: 8),
              const Text('Manual Override'),
            ],
          ),
          const SizedBox(height: 16),
          SearchableField(
            label: 'Rasi',
            isRequired: true,
            items: AppConstants.rasiList,
            selectedItem: _rasi,
            prefixIcon: Icons.brightness_3_outlined,
            onChanged: (v) => setState(() => _rasi = v),
          ),
          const SizedBox(height: 16),
          SearchableField(
            label: 'Nakshatra',
            isRequired: true,
            items: AppConstants.nakshatraList,
            selectedItem: _nakshatra,
            prefixIcon: Icons.star_outline,
            onChanged: (v) => setState(() => _nakshatra = v),
          ),
          const SizedBox(height: 16),
          SearchableField(
            label: 'Lagnam',
            items: AppConstants.lagnamList,
            selectedItem: _lagnam,
            onChanged: (v) => setState(() => _lagnam = v),
          ),
          if (_rasi != null || _nakshatra != null) ...[
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.amber[50],
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.amber[200]!),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('⚠️ Astrologer Verification', style: TextStyle(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 4),
                  const Text(
                    'An astrologer will verify your horoscope details. You will be notified after verification.',
                    style: TextStyle(fontSize: 13, color: Colors.grey),
                  ),
                ],
              ),
            ),
          ],
          const SizedBox(height: 32),
          GradientButton(onPressed: _saveAndNext, text: 'Next'),
        ],
      ),
    );
  }

}
