#!/usr/bin/env python3
"""Regenerate every icon in the project from the ONE brand logo.

There is a single source of truth — `assets/images/app_logo.png` — and this
script derives all three consumers from it, so the in-app mark, the home-screen
icon and the Play Store listing icon can never drift apart:

  1. Legacy launcher icons   android/.../mipmap-<d>/ic_launcher.png
  2. Adaptive icon foreground android/.../drawable-<d>/ic_launcher_foreground.png
     + mipmap-anydpi-v26/ic_launcher.xml
  3. Play Console hi-res icon branding/play_store_icon_512.png

Why it is not just "resize the PNG five times":

  * The artwork is a rounded red plate that sits inside a transparent margin.
    `BoxFit.cover` widgets and the Android masks both want a FULL-BLEED square,
    so the margin is trimmed off first (`--write-master` bakes the trim back
    into the master itself).
  * Android masks an adaptive icon down to the middle ~66 of its 108 units, and
    the gold artwork already fills 85% of the plate — full-bleed would put the
    zodiac wheel's outer stars straight under the mask. So the foreground
    shrinks the plate into the safe zone and paints the freed ring with the
    plate's OWN radial colour profile, sampled from the red showing between the
    wheel's spokes. Extending it with a flat colour instead leaves a visible
    rounded-square seam, because the plate is a gradient, not a solid fill.
  * Play rejects/dulls transparency in the hi-res icon, so that one is
    flattened onto the plate's red. It stays full-bleed: the Store only rounds
    the corners, it does not crop a third of the icon away like a launcher.

Usage:
    python tool/generate_brand_icons.py [SOURCE_IMAGE] [--write-master]

SOURCE_IMAGE defaults to assets/images/app_logo.png. Pass a freshly exported
logo plus --write-master to adopt a NEW logo across the whole project in one
command. Requires Pillow (pip install pillow); no Flutter/Android SDK needed.
"""
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.join(ROOT, "assets", "images", "app_logo.png")
RES = os.path.join(ROOT, "android", "app", "src", "main", "res")
BRANDING = os.path.join(ROOT, "branding")

LEGACY_PX = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
FOREGROUND_PX = {"mdpi": 108, "hdpi": 162, "xhdpi": 216, "xxhdpi": 324,
                 "xxxhdpi": 432}

# Android reserves the outer ring of an adaptive icon for masking: of the 108
# design units only the middle 72 are guaranteed visible, and launchers that
# use a circle eat into that further. Keeping the artwork at 60/108 leaves a
# comfortable margin on every mask shape.
SAFE_FRACTION = 60 / 108

# Where the real plate dissolves into the synthesised gradient, as a fraction of
# the plate's half-width. The gold artwork reaches ~0.85, so the ramp has to
# start above that or it would fade the wheel's outer stars.
FEATHER_START = 0.88
FEATHER_END = 1.0

MASTER_PX = 1024
PLAY_PX = 512

ADAPTIVE_XML = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<!-- Generated by tool/generate_brand_icons.py - do not hand-edit. -->\n'
    '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
    '  <background android:drawable="@color/ic_launcher_background"/>\n'
    '  <!-- No <inset> here on purpose: the safe-zone margin is baked into the\n'
    '       foreground bitmap itself, together with the gradient that fills it.\n'
    '       Re-adding an inset would shrink the artwork a second time and put a\n'
    '       flat-colour ring back around the plate. -->\n'
    '  <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
    "</adaptive-icon>\n"
)


def _is_plate(px):
    """Opaque brand-red pixel — excludes the soft drop shadow under the plate."""
    r, g, b, a = px
    return a > 250 and r > 55 and r > g + 25


def plate_box(im):
    """Tight bounds of the red plate, ignoring transparent margin and shadow."""
    w, h = im.size
    px = im.load()
    xs, ys = [], []
    for y in range(h):
        for x in range(w):
            if _is_plate(px[x, y]):
                xs.append(x)
                ys.append(y)
    if not xs:
        sys.exit("ERROR: no opaque brand-red plate found in the source image.")
    return min(xs), min(ys), max(xs), max(ys)


def art_box(im):
    """Tight bounds of the gold artwork (wheel, stars, couple, infinity)."""
    w, h = im.size
    px = im.load()
    xs, ys = [], []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a > 250 and g > 110 and r > 140:
                xs.append(x)
                ys.append(y)
    if not xs:
        sys.exit("ERROR: no gold artwork found in the source image.")
    return min(xs), min(ys), max(xs), max(ys)


def _is_bare_red(px):
    """Plate red with no gold on top — the raw background of the artwork."""
    r, g, b, a = px
    return a > 250 and r > 55 and g < 45 and r > g + 25


def radial_profile(plate, bands=96):
    """Median plate red at each radius, sampled between the wheel's spokes.

    Returns `bands` RGB triples from the centre outwards. Bands with too few
    bare-red pixels (where gold covers the full ring) inherit their neighbour,
    so the profile is always complete and monotonic-ish.
    """
    side = plate.size[0]
    px = plate.load()
    c = (side - 1) / 2
    buckets = [[] for _ in range(bands)]
    for y in range(side):
        dy = y - c
        for x in range(side):
            p = px[x, y]
            if not _is_bare_red(p):
                continue
            d = ((x - c) ** 2 + dy ** 2) ** 0.5 / c
            i = int(d * (bands - 1))
            if i < bands:
                buckets[i].append(p[:3])

    profile = [None] * bands
    for i, vals in enumerate(buckets):
        if len(vals) >= 8:
            vals.sort(key=lambda t: t[0] + t[1] + t[2])
            profile[i] = vals[len(vals) // 2]
    known = [i for i, v in enumerate(profile) if v]
    if not known:
        sys.exit("ERROR: could not sample the plate's colour profile.")
    for i in range(bands):  # fill gaps from the nearest sampled band
        if profile[i] is None:
            profile[i] = profile[min(known, key=lambda k: abs(k - i))]
    # Light smoothing so banding never shows in the synthesised ring.
    smooth = []
    for i in range(bands):
        lo, hi = max(0, i - 3), min(bands, i + 4)
        win = profile[lo:hi]
        smooth.append(tuple(sum(c[j] for c in win) // len(win) for j in range(3)))
    return smooth


def synth_plate_field(profile, size, plate_half):
    """Full-bleed red field following the plate's radial profile.

    Beyond the plate's own radius the outermost sampled colour is held, so the
    gradient simply stops deepening instead of ending at a hard edge.
    """
    bands = len(profile)
    field = Image.new("RGB", (size, size))
    out = field.load()
    c = (size - 1) / 2
    for y in range(size):
        dy = y - c
        for x in range(size):
            d = ((x - c) ** 2 + dy ** 2) ** 0.5 / plate_half
            out[x, y] = profile[min(bands - 1, int(d * (bands - 1)))]
    return field


def _feather_mask(size, start, end):
    """Circular alpha ramp: opaque inside `start`, clear past `end` (0..1 of R)."""
    mask = Image.new("L", (size, size))
    out = mask.load()
    c = (size - 1) / 2
    for y in range(size):
        dy = y - c
        for x in range(size):
            d = ((x - c) ** 2 + dy ** 2) ** 0.5 / c
            if d <= start:
                out[x, y] = 255
            elif d >= end:
                out[x, y] = 0
            else:
                out[x, y] = int(255 * (end - d) / (end - start))
    return mask


def edge_colour(im, box):
    """Average plate colour just inside its border — the flat-fill fallback."""
    px = im.load()
    x0, y0, x1, y1 = box
    inset = max(2, (x1 - x0) // 40)
    samples = []
    for x in range(x0 + inset * 3, x1 - inset * 3):
        for y in (y0 + inset, y1 - inset):
            if _is_plate(px[x, y]):
                samples.append(px[x, y][:3])
    for y in range(y0 + inset * 3, y1 - inset * 3):
        for x in (x0 + inset, x1 - inset):
            if _is_plate(px[x, y]):
                samples.append(px[x, y][:3])
    n = len(samples)
    return tuple(sum(c[i] for c in samples) // n for i in range(3))


def square_plate(im):
    """The plate as a full-bleed square, centred on the artwork.

    Uses the plate's width as the square's side (its height picks up a few rows
    of drop shadow) and re-centres horizontally on the plate, vertically on the
    artwork, so the wheel sits in the middle of the icon.

    A source whose plate already touches all four edges is returned untouched.
    Without that guard the crop would shift a little further up on every run —
    and since the master IS this script's default input, re-running it would
    slowly eat into the artwork.
    """
    w, h = im.size
    p = plate_box(im)
    tol = max(2, w // 50)
    if (w == h and p[0] <= tol and p[1] <= tol
            and p[2] >= w - 1 - tol and p[3] >= h - 1 - tol):
        return im.copy()

    a = art_box(im)
    side = p[2] - p[0] + 1
    cx = (p[0] + p[2]) // 2
    cy = (a[1] + a[3]) // 2
    top = max(p[1], min(cy - side // 2, p[3] - side + 1))
    return im.crop((cx - side // 2, top, cx - side // 2 + side, top + side))


def safe_foreground(plate, profile, px_size):
    """Opaque full-bleed adaptive foreground with the art inside the safe zone.

    The plate is scaled until the gold artwork spans SAFE_FRACTION of the
    canvas, feathered off just outside the artwork, and laid over a synthesised
    continuation of its own radial gradient — so the icon reads as one seamless
    plate while no mask shape can clip the zodiac wheel or its stars.
    """
    a = art_box(plate)
    art_side = max(a[2] - a[0] + 1, a[3] - a[1] + 1)

    scale = (px_size * SAFE_FRACTION) / art_side
    plate_px = max(1, round(plate.size[0] * scale))
    scaled = plate.resize((plate_px, plate_px), Image.LANCZOS).convert("RGB")

    # Fade the real plate out between the artwork's rim and the plate's edge,
    # which also disposes of its rounded corners and drop shadow.
    scaled.putalpha(_feather_mask(plate_px, FEATHER_START, FEATHER_END))

    canvas = synth_plate_field(profile, px_size, plate_px / 2).convert("RGBA")
    # Centre on the ARTWORK's centre, not the plate's: the plate carries extra
    # height below the wheel, and the mask is centred on the canvas.
    acx = (a[0] + a[2]) / 2 * scale
    acy = (a[1] + a[3]) / 2 * scale
    canvas.alpha_composite(scaled,
                           (round(px_size / 2 - acx), round(px_size / 2 - acy)))
    return canvas.convert("RGB")


def play_icon(plate, fill, px_size):
    """Full-bleed 512 store icon: the plate itself, flattened (Play bans alpha).

    Only the plate's rounded corners need filling, and the Store rounds those
    off again when it renders the listing.
    """
    flat = Image.new("RGBA", plate.size, fill + (255,))
    flat.alpha_composite(plate)
    return flat.convert("RGB").resize((px_size, px_size), Image.LANCZOS)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    write_master = "--write-master" in sys.argv
    src_path = args[0] if args else MASTER

    if not os.path.exists(src_path):
        sys.exit(f"ERROR: source image not found:\n  {src_path}")

    src = Image.open(src_path).convert("RGBA")
    print(f"source: {src_path}  {src.size[0]}x{src.size[1]}")
    p, a = plate_box(src), art_box(src)
    fill = edge_colour(src, p)
    print(f"  plate box {p}   gold-art box {a}")
    print("  plate edge colour  #%02X%02X%02X" % fill)

    plate = square_plate(src)
    print(f"  squared plate      {plate.size[0]}x{plate.size[1]}")

    if write_master:
        os.makedirs(os.path.dirname(MASTER), exist_ok=True)
        plate.resize((MASTER_PX, MASTER_PX), Image.LANCZOS).save(MASTER)
        print(f"  master     assets/images/app_logo.png  {MASTER_PX}px")
        src = Image.open(MASTER).convert("RGBA")
        plate = square_plate(src)
        fill = edge_colour(src, plate_box(src))

    profile = radial_profile(plate)
    print("  radial profile     centre #%02X%02X%02X -> rim #%02X%02X%02X"
          % (profile[0] + profile[-1]))

    # 1. Legacy launcher icons — the plate as-is, rounded corners intact.
    for d, size in LEGACY_PX.items():
        out = os.path.join(RES, f"mipmap-{d}", "ic_launcher.png")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        plate.resize((size, size), Image.LANCZOS).save(out)
        print(f"  legacy     mipmap-{d}/ic_launcher.png  {size}px")

    # 2. Adaptive foreground — safe-zone fitted, opaque, seamless gradient.
    for d, size in FOREGROUND_PX.items():
        out = os.path.join(RES, f"drawable-{d}", "ic_launcher_foreground.png")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        safe_foreground(plate, profile, size).save(out)
        print(f"  foreground drawable-{d}/ic_launcher_foreground.png  {size}px")

    xml_out = os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher.xml")
    os.makedirs(os.path.dirname(xml_out), exist_ok=True)
    with open(xml_out, "w", encoding="utf-8") as f:
        f.write(ADAPTIVE_XML)
    print("  adaptive   mipmap-anydpi-v26/ic_launcher.xml")

    # 3. Play Console hi-res icon — 512x512, full-bleed, no alpha.
    os.makedirs(BRANDING, exist_ok=True)
    play_out = os.path.join(BRANDING, "play_store_icon_512.png")
    play_icon(plate, fill, PLAY_PX).save(play_out)
    print(f"  play       branding/play_store_icon_512.png  {PLAY_PX}px")

    print("\nDONE. @color/ic_launcher_background should be the rim colour "
          "printed above; rebuild to see the new icon.")


if __name__ == "__main__":
    main()
