class AppConstants {
  static const String appName = 'Jothida Matrimony';
  static const String appTagline = 'ஜோதிட மேட்ரிமோனி';
  static const String appVersion = '1.0.0';

  // Firestore Collections
  static const String usersCollection = 'users';
  static const String profilesCollection = 'profiles';
  static const String interestsCollection = 'interests';
  static const String subscriptionsCollection = 'subscriptions';
  static const String poruthamsCollection = 'poruthams';
  static const String reportsCollection = 'reports';
  static const String notificationsCollection = 'notifications';
  static const String transactionsCollection = 'transactions';
  static const String adminCollection = 'admin';

  // Storage Paths
  static const String profilePhotosPath = 'profile_photos';
  static const String horoscopeDocsPath = 'horoscope_docs';
  static const String idProofsPath = 'id_proofs';

  // Subscription Plans
  static const String planBasic = 'basic';
  static const String planMedium = 'medium';
  static const String planPremium = 'premium';

  // Plan Prices (INR)
  static const int basicPrice = 99;
  static const int mediumPrice = 299;
  static const int premiumPrice = 599;
  static const int poruthamsPrice = 199;
  static const int freePortuthamsPerMedium = 2;

  // Basic Plan Limits
  static const int basicDailyProfileViews = 10;
  static const int basicMonthlyInterests = 5;

  // Pagination
  static const int profilesPerPage = 20;
  static const int notificationsPerPage = 30;

  // Interest Status
  static const String interestPending = 'pending';
  static const String interestAccepted = 'accepted';
  static const String interestRejected = 'rejected';

  // Profile Status
  static const String profilePending = 'pending';
  static const String profileApproved = 'approved';
  static const String profileRejected = 'rejected';
  static const String profileBlocked = 'blocked';

  // User Roles
  static const String roleUser = 'user';
  static const String roleAdmin = 'admin';
  static const String roleAstrologer = 'astrologer';

  // Porutham Status
  static const String poruthamsRequested = 'requested';
  static const String poruthamsCompleted = 'completed';

  // Horoscope Badges
  static const String badgeAutoGenerated = 'auto_generated';
  static const String badgeUserEdited = 'user_edited';
  static const String badgeAstrologerVerified = 'astrologer_verified';

  // Report Levels
  static const int reportWarningThreshold = 3;
  static const int reportHighThreshold = 5;
  static const int reportCriticalThreshold = 10;

  // Tamil Rasi List
  static const List<String> rasiList = [
    'மேஷம்', 'ரிஷபம்', 'மிதுனம்', 'கடகம்',
    'சிம்மம்', 'கன்னி', 'துலாம்', 'விருச்சிகம்',
    'தனுசு', 'மகரம்', 'கும்பம்', 'மீனம்',
  ];

  // English Rasi List
  static const List<String> rasiEnList = [
    'Mesham (Aries)', 'Rishabam (Taurus)', 'Midhunam (Gemini)', 'Kadagam (Cancer)',
    'Simmam (Leo)', 'Kanni (Virgo)', 'Thulam (Libra)', 'Viruchigam (Scorpio)',
    'Dhanusu (Sagittarius)', 'Magaram (Capricorn)', 'Kumbam (Aquarius)', 'Meenam (Pisces)',
  ];

  // Nakshatra List
  static const List<String> nakshatraList = [
    'அஸ்வினி', 'பரணி', 'கார்த்திகை', 'ரோகிணி', 'மிருகசீரிஷம்',
    'திருவாதிரை', 'புனர்பூசம்', 'பூசம்', 'ஆயில்யம்', 'மகம்',
    'பூரம்', 'உத்திரம்', 'அஸ்தம்', 'சித்திரை', 'சுவாதி',
    'விசாகம்', 'அனுஷம்', 'கேட்டை', 'மூலம்', 'பூராடம்',
    'உத்திராடம்', 'திருவோணம்', 'அவிட்டம்', 'சதயம்',
    'பூரட்டாதி', 'உத்திரட்டாதி', 'ரேவதி',
  ];

  // Lagnam List
  static const List<String> lagnamList = [
    'மேஷம்', 'ரிஷபம்', 'மிதுனம்', 'கடகம்',
    'சிம்மம்', 'கன்னி', 'துலாம்', 'விருச்சிகம்',
    'தனுசு', 'மகரம்', 'கும்பம்', 'மீனம்',
  ];

  // Dasa List
  static const List<String> dasaList = [
    'சூரியன்', 'சந்திரன்', 'செவ்வாய்', 'ராகு',
    'குரு', 'சனி', 'புதன்', 'கேது', 'சுக்கிரன்',
  ];

  // Religion List
  static const List<String> religionList = [
    'Hindu', 'Muslim', 'Christian', 'Sikh', 'Buddhist', 'Jain', 'Other',
  ];

  // Caste List (Hindu)
  static const List<String> castList = [
    'Brahmin', 'Kshatriya', 'Vaisya', 'Nadar', 'Thevar', 'Gounder',
    'Mudaliar', 'Chettiar', 'Pillai', 'Yadav', 'Naicker', 'Vellalar',
    'Paraiyar', 'Pallar', 'Kallar', 'Agamudayar', 'Maravar', 'Servai',
    'Any Caste', 'Other',
  ];

  // Marital Status
  static const List<String> maritalStatusList = [
    'Never Married', 'Divorced', 'Widowed', 'Awaiting Divorce',
  ];

  // Education List
  static const List<String> educationList = [
    'SSLC', 'HSC', 'Diploma', 'B.E / B.Tech', 'B.Sc', 'B.Com', 'B.A',
    'BCA', 'BBA', 'M.E / M.Tech', 'M.Sc', 'M.Com', 'M.A', 'MBA', 'MCA',
    'MBBS', 'MD', 'B.Pharm', 'LLB', 'Ph.D', 'Other',
  ];

  // Occupation List
  static const List<String> occupationList = [
    'Software Engineer', 'Doctor', 'Engineer', 'Teacher', 'Professor',
    'Lawyer', 'Chartered Accountant', 'Government Employee', 'Business',
    'Self Employed', 'Army / Police', 'Nurse', 'Pharmacist', 'Architect',
    'Banker', 'Journalist', 'Actor / Artist', 'Not Working', 'Other',
  ];

  // Family Type
  static const List<String> familyTypeList = [
    'Joint Family', 'Nuclear Family',
  ];

  // Family Status
  static const List<String> familyStatusList = [
    'Rich', 'Upper Middle Class', 'Middle Class', 'Lower Middle Class',
  ];

  // Income List
  static const List<String> incomeList = [
    'Below ₹1 Lakh', '₹1-2 Lakhs', '₹2-3 Lakhs', '₹3-5 Lakhs',
    '₹5-7 Lakhs', '₹7-10 Lakhs', '₹10-15 Lakhs', '₹15-20 Lakhs',
    '₹20-30 Lakhs', '₹30-50 Lakhs', 'Above ₹50 Lakhs',
  ];

  // Mother Tongue
  static const List<String> motherTongueList = [
    'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Hindi', 'Marathi',
    'Bengali', 'Gujarati', 'Punjabi', 'Urdu', 'Other',
  ];

  // Report Reasons
  static const List<String> reportReasons = [
    'Fake Profile', 'Wrong Information', 'Harassment',
    'Scam', 'Inappropriate Content', 'Other',
  ];

  // Porutham Types
  static const List<String> poruthamsTypes = [
    'Dina Porutham', 'Gana Porutham', 'Mahendra Porutham',
    'Rajju Porutham', 'Yoni Porutham', 'Rasi Porutham',
  ];

  // Profile Created By
  static const List<String> profileCreatedByList = [
    'Myself', 'Son', 'Daughter', 'Brother', 'Sister', 'Relative',
  ];

  // Height Range
  static const List<String> heightList = [
    "4'6\"", "4'7\"", "4'8\"", "4'9\"", "4'10\"", "4'11\"",
    "5'0\"", "5'1\"", "5'2\"", "5'3\"", "5'4\"", "5'5\"",
    "5'6\"", "5'7\"", "5'8\"", "5'9\"", "5'10\"", "5'11\"",
    "6'0\"", "6'1\"", "6'2\"", "6'3\"", "6'4\"", "6'5\"",
  ];

  // Country List (common)
  static const List<String> countryList = [
    'India', 'USA', 'UK', 'Canada', 'Australia', 'UAE', 'Singapore',
    'Malaysia', 'Germany', 'France', 'Other',
  ];

  // Indian States
  static const List<String> indianStates = [
    'Tamil Nadu', 'Andhra Pradesh', 'Karnataka', 'Kerala', 'Telangana',
    'Maharashtra', 'Gujarat', 'Rajasthan', 'Uttar Pradesh', 'Madhya Pradesh',
    'West Bengal', 'Bihar', 'Odisha', 'Punjab', 'Haryana', 'Delhi',
    'Himachal Pradesh', 'Uttarakhand', 'Goa', 'Chhattisgarh', 'Jharkhand',
    'Assam', 'Other',
  ];
}
